package com.example.plate.controller;

import java.util.List;

import org.springframework.boot.ApplicationArguments;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.example.plate.entity.Items;

import springfox.documentation.spring.web.json.Json;

@RestController
@RequestMapping(value = "/company")
//@CrossOrigin(origins = "http://localhost:3000")
public class OrderController {
	
	
	@RequestMapping(value = "/order/{id}", method = RequestMethod.GET,produces =  MediaType.APPLICATION_JSON_VALUE )
	public ResponseEntity<String> fetchAllItems(@PathVariable(required = false) String id) {
		String s="[\r\n"
				+ "    {\r\n"
				+ "        \"id\": \"ochOrder::fc3545be-8042-4f38-ad06-21a5eb9c3c41::v1\",\r\n"
				+ "        \"type\": \"order\",\r\n"
				+ "        \"typeVersion\": \"v1\",\r\n"
				+ "        \"orderUniqueId\": \"ochOrder::fc3545be-8042-4f38-ad06-21a5eb9c3c41::v1\",\r\n"
				+ "        \"receivedDateTime\": \"2023-09-05T13:50:03.094Z\",\r\n"
				+ "        \"updatedDateTime\": \"2023-09-05T13:50:03.344Z\",\r\n"
				+ "        \"createdDateTime\": \"2023-09-05T13:49:02Z\",\r\n"
				+ "        \"sourceOrderId\": \"1693921733598\",\r\n"
				+ "        \"reasonDescription\": \"Order received succesfully\",\r\n"
				+ "        \"statusCode\": \"INPROCESS\",\r\n"
				+ "        \"orderProcessingStatus\": \"ORDER_RECEIVED\",\r\n"
				+ "        \"orderProcessingStatusReason\": \"Order validation successful\",\r\n"
				+ "        \"orderPaymentStatus\": \"PENDING\",\r\n"
				+ "        \"countryIsoCode\": \"US\",\r\n"
				+ "        \"companyCode\": \"1\",\r\n"
				+ "        \"sourceSystemId\": \"626\",\r\n"
				+ "        \"orderChannelMethodCode\": \"web\",\r\n"
				+ "        \"soldToCustomerId\": \"42358780\",\r\n"
				+ "        \"orderTypeCode\": \"06\",\r\n"
				+ "        \"orderSubTypeCode\": \"SellerManaged\",\r\n"
				+ "        \"privateRemarksText\": \"\",\r\n"
				+ "        \"requestedDeliveryDateTime\": \"2023-09-06T13:50:03.427Z\",\r\n"
				+ "        \"totalRequestedQty\": 16,\r\n"
				+ "        \"totalGrossAmount\": 36.68,\r\n"
				+ "        \"totalDiscountAmount\": 0.0,\r\n"
				+ "        \"totalTaxAmount\": 3.5,\r\n"
				+ "        \"netTotalAmount\": 40.18,\r\n"
				+ "        \"consumerPaidShippingAmount\": 0.0,\r\n"
				+ "        \"currencyCode\": \"USD\",\r\n"
				+ "        \"orderTagsText\": \"Regular\",\r\n"
				+ "        \"marketPlaceAccountId\": \"9999\",\r\n"
				+ "        \"sourceProfileId\": \"9999\",\r\n"
				+ "        \"marketPlaceOrderId\": \"1693921733598\",\r\n"
				+ "        \"marketPlaceAlternateOrderId\": \"995\",\r\n"
				+ "        \"routeId\": \"R00551\",\r\n"
				+ "        \"orderLocationId\": \"12212\",\r\n"
				+ "        \"referenceOrderId\": \"0000922768\",\r\n"
				+ "        \"customerRemarksText\": \"\",\r\n"
				+ "        \"languageIsoCode\": \"EN\",\r\n"
				+ "        \"sourceSystemName\": \"D2C\",\r\n"
				+ "        \"createdById\": \"0oappd8cznzjYOBaX0h7\",\r\n"
				+ "        \"orderType\": \"ZWO\",\r\n"
				+ "        \"orderSubStatus\": \"VALIDATED\",\r\n"
				+ "        \"extendedAttributesMap\": {\r\n"
				+ "            \"addressVerificationRequired\": false,\r\n"
				+ "            \"salesforceOrderId\": \"801Dh000002dm0SIAQ\",\r\n"
				+ "            \"deliveryId\": null,\r\n"
				+ "            \"additionalEmails\": \"\",\r\n"
				+ "            \"ipAddress\": \"MTQ4LjY0LjUuMjI=\",\r\n"
				+ "            \"fraudCheck\": false,\r\n"
				+ "            \"preOrder\": false,\r\n"
				+ "            \"mdgLocationId\": \"2116\",\r\n"
				+ "            \"sessionId\": \"1693921633032\",\r\n"
				+ "            \"mdgCustomerId\": \"2003772961\",\r\n"
				+ "            \"mdgRouteId\": \"USF05F\"\r\n"
				+ "        },\r\n"
				+ "        \"isMixedCpgOrder\": false,\r\n"
				+ "        \"extendedAttributesList\": [],\r\n"
				+ "        \"consumerProfile\": {\r\n"
				+ "            \"consumerProfileId\": \"8a5b9d8888434bdd018843a3921c0001\",\r\n"
				+ "            \"consumerEmailText\": \"nidanelson246+2@gmail.com\",\r\n"
				+ "            \"firstName\": \"Peter\",\r\n"
				+ "            \"lastName\": \"Sutherland\",\r\n"
				+ "            \"phoneNumber\": \"9161071420\",\r\n"
				+ "            \"consumerRegisteredFlag\": \"true\"\r\n"
				+ "        },\r\n"
				+ "        \"addresses\": [\r\n"
				+ "            {\r\n"
				+ "                \"addressType\": \"Shipping\",\r\n"
				+ "                \"firstName\": \"Peter\",\r\n"
				+ "                \"lastName\": \"Sutherland\",\r\n"
				+ "                \"addressLine1\": \"1610 East Florence Avenue\",\r\n"
				+ "                \"addressLine2\": \"\",\r\n"
				+ "                \"cityName\": \"Los Angeles\",\r\n"
				+ "                \"stateOrProvinceName\": \"CA\",\r\n"
				+ "                \"postalArea\": \"90001\",\r\n"
				+ "                \"countryIsoName\": \"US\",\r\n"
				+ "                \"deliveryInstructions\": \"\"\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"addressType\": \"Billing\",\r\n"
				+ "                \"firstName\": \"Peter\",\r\n"
				+ "                \"lastName\": \"Sutherland\",\r\n"
				+ "                \"addressLine1\": \"1610 East Florence Avenue\",\r\n"
				+ "                \"addressLine2\": \"\",\r\n"
				+ "                \"cityName\": \"Los Angeles\",\r\n"
				+ "                \"stateOrProvinceName\": \"CA\",\r\n"
				+ "                \"postalArea\": \"90001\",\r\n"
				+ "                \"countryIsoName\": \"US\",\r\n"
				+ "                \"daytimeTelephoneNumber\": \"\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"consumerPayments\": [\r\n"
				+ "            {\r\n"
				+ "                \"paymentTransactionId\": \"6939217339146046903954\",\r\n"
				+ "                \"paymentTransactionAccountId\": \"\",\r\n"
				+ "                \"transactionDateTime\": \"2023-09-05T13:49:02Z\",\r\n"
				+ "                \"paymentMethodCode\": \"card\",\r\n"
				+ "                \"paymentTransactionAmount\": 40.18,\r\n"
				+ "                \"paymentTransactionValue\": \"ACCEPTED\",\r\n"
				+ "                \"transactionMerchantReferenceNumber\": \"753551224M4MPTMI\",\r\n"
				+ "                \"paymentTransactionSystem\": \"CyberSource\"\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"items\": [\r\n"
				+ "            {\r\n"
				+ "                \"sourceOrderLineId\": \"348511\",\r\n"
				+ "                \"materialId\": \"00028400642040\",\r\n"
				+ "                \"requestedQty\": 4,\r\n"
				+ "                \"requestedQtyUom\": \"EA\",\r\n"
				+ "                \"unitPriceAmount\": 2.29,\r\n"
				+ "                \"totalGrossAmount\": 9.16,\r\n"
				+ "                \"totalTaxAmount\": 0.88,\r\n"
				+ "                \"isBundleFlag\": false,\r\n"
				+ "                \"sourceProductId\": \"08652301\",\r\n"
				+ "                \"lineMaterialTypeCode\": \"01\",\r\n"
				+ "                \"requestedMaterialId\": \"08652301\",\r\n"
				+ "                \"requestedMaterialName\": \"Doritos Tortilla Chips Spicy Nacho 9 3/4 Oz\",\r\n"
				+ "                \"totalNetAmount\": 10.04,\r\n"
				+ "                \"pepMaterialId\": \"00028400642040\",\r\n"
				+ "                \"productClass\": \"CLASS\",\r\n"
				+ "                \"taxDetails\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0025,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.06,\r\n"
				+ "                        \"taxAmount\": 0.55,\r\n"
				+ "                        \"taxTypeCode\": \"STATE\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0125,\r\n"
				+ "                        \"taxAmount\": 0.11,\r\n"
				+ "                        \"taxTypeCode\": \"COUNTY\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"discountDetails\": [],\r\n"
				+ "                \"fulfillments\": [],\r\n"
				+ "                \"bundleComponents\": [],\r\n"
				+ "                \"adjustments\": [],\r\n"
				+ "                \"extendedItemAttributesMap\": {\r\n"
				+ "                    \"mdgRequestedQtyUom\": \"EA\",\r\n"
				+ "                    \"sourceProfileId\": \"9999\",\r\n"
				+ "                    \"routeId\": \"R00551\",\r\n"
				+ "                    \"marketPlaceAlternateOrderId\": \"995\",\r\n"
				+ "                    \"orderLocationId\": \"12212\",\r\n"
				+ "                    \"soldToCustomerId\": \"42358780\",\r\n"
				+ "                    \"preOrder\": false,\r\n"
				+ "                    \"mdgLocationId\": \"2116\",\r\n"
				+ "                    \"mdgProductId\": \"000000000300022362\",\r\n"
				+ "                    \"mdgRouteId\": \"USF05F\",\r\n"
				+ "                    \"marketPlaceAccountId\": \"9999\"\r\n"
				+ "                },\r\n"
				+ "                \"extendedItemAttributesList\": []\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"sourceOrderLineId\": \"348512\",\r\n"
				+ "                \"materialId\": \"00028400459587\",\r\n"
				+ "                \"requestedQty\": 4,\r\n"
				+ "                \"requestedQtyUom\": \"PAK\",\r\n"
				+ "                \"unitPriceAmount\": 0.99,\r\n"
				+ "                \"totalGrossAmount\": 3.96,\r\n"
				+ "                \"totalTaxAmount\": 0.38,\r\n"
				+ "                \"isBundleFlag\": false,\r\n"
				+ "                \"sourceProductId\": \"08353700\",\r\n"
				+ "                \"lineMaterialTypeCode\": \"01\",\r\n"
				+ "                \"requestedMaterialId\": \"08353700\",\r\n"
				+ "                \"requestedMaterialName\": \"Nut Harvest Pistachios In Shell Salted 1 3/4 Oz\",\r\n"
				+ "                \"totalNetAmount\": 4.34,\r\n"
				+ "                \"pepMaterialId\": \"00028400459587\",\r\n"
				+ "                \"productClass\": \"CLASS\",\r\n"
				+ "                \"taxDetails\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0025,\r\n"
				+ "                        \"taxAmount\": 0.01,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0125,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"COUNTY\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.06,\r\n"
				+ "                        \"taxAmount\": 0.24,\r\n"
				+ "                        \"taxTypeCode\": \"STATE\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"discountDetails\": [],\r\n"
				+ "                \"fulfillments\": [],\r\n"
				+ "                \"bundleComponents\": [],\r\n"
				+ "                \"adjustments\": [],\r\n"
				+ "                \"extendedItemAttributesMap\": {\r\n"
				+ "                    \"mdgRequestedQtyUom\": \"EA\",\r\n"
				+ "                    \"sourceProfileId\": \"9999\",\r\n"
				+ "                    \"routeId\": \"R00551\",\r\n"
				+ "                    \"marketPlaceAlternateOrderId\": \"995\",\r\n"
				+ "                    \"orderLocationId\": \"12212\",\r\n"
				+ "                    \"soldToCustomerId\": \"42358780\",\r\n"
				+ "                    \"preOrder\": false,\r\n"
				+ "                    \"mdgLocationId\": \"2116\",\r\n"
				+ "                    \"mdgProductId\": \"000000000300021591\",\r\n"
				+ "                    \"mdgRouteId\": \"USF05F\",\r\n"
				+ "                    \"marketPlaceAccountId\": \"9999\"\r\n"
				+ "                },\r\n"
				+ "                \"extendedItemAttributesList\": []\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"sourceOrderLineId\": \"348513\",\r\n"
				+ "                \"materialId\": \"00028400437929\",\r\n"
				+ "                \"requestedQty\": 4,\r\n"
				+ "                \"requestedQtyUom\": \"EA\",\r\n"
				+ "                \"unitPriceAmount\": 3.49,\r\n"
				+ "                \"totalGrossAmount\": 13.96,\r\n"
				+ "                \"totalTaxAmount\": 1.32,\r\n"
				+ "                \"isBundleFlag\": false,\r\n"
				+ "                \"sourceProductId\": \"08073501\",\r\n"
				+ "                \"lineMaterialTypeCode\": \"01\",\r\n"
				+ "                \"requestedMaterialId\": \"08073501\",\r\n"
				+ "                \"requestedMaterialName\": \"Sabritas Fiesta Mix Flavored Snack Mix 2.75 Oz\",\r\n"
				+ "                \"totalNetAmount\": 15.28,\r\n"
				+ "                \"pepMaterialId\": \"00028400437929\",\r\n"
				+ "                \"productClass\": \"CLASS\",\r\n"
				+ "                \"taxDetails\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.06,\r\n"
				+ "                        \"taxAmount\": 0.84,\r\n"
				+ "                        \"taxTypeCode\": \"STATE\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0125,\r\n"
				+ "                        \"taxAmount\": 0.17,\r\n"
				+ "                        \"taxTypeCode\": \"COUNTY\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.07,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.07,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.07,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.07,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0025,\r\n"
				+ "                        \"taxAmount\": 0.03,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"discountDetails\": [],\r\n"
				+ "                \"fulfillments\": [],\r\n"
				+ "                \"bundleComponents\": [],\r\n"
				+ "                \"adjustments\": [],\r\n"
				+ "                \"extendedItemAttributesMap\": {\r\n"
				+ "                    \"mdgRequestedQtyUom\": \"EA\",\r\n"
				+ "                    \"sourceProfileId\": \"9999\",\r\n"
				+ "                    \"routeId\": \"R00551\",\r\n"
				+ "                    \"marketPlaceAlternateOrderId\": \"995\",\r\n"
				+ "                    \"orderLocationId\": \"12212\",\r\n"
				+ "                    \"soldToCustomerId\": \"42358780\",\r\n"
				+ "                    \"preOrder\": false,\r\n"
				+ "                    \"mdgLocationId\": \"2116\",\r\n"
				+ "                    \"mdgProductId\": \"000000000300021052\",\r\n"
				+ "                    \"mdgRouteId\": \"USF05F\",\r\n"
				+ "                    \"marketPlaceAccountId\": \"9999\"\r\n"
				+ "                },\r\n"
				+ "                \"extendedItemAttributesList\": []\r\n"
				+ "            },\r\n"
				+ "            {\r\n"
				+ "                \"sourceOrderLineId\": \"348514\",\r\n"
				+ "                \"materialId\": \"00028400695312\",\r\n"
				+ "                \"requestedQty\": 4,\r\n"
				+ "                \"unitPriceAmount\": 2.4,\r\n"
				+ "                \"totalGrossAmount\": 9.6,\r\n"
				+ "                \"totalTaxAmount\": 0.92,\r\n"
				+ "                \"isBundleFlag\": false,\r\n"
				+ "                \"sourceProductId\": \"1500000641\",\r\n"
				+ "                \"lineMaterialTypeCode\": \"01\",\r\n"
				+ "                \"requestedMaterialId\": \"1500000641\",\r\n"
				+ "                \"requestedMaterialName\": \"BANDANA\",\r\n"
				+ "                \"totalNetAmount\": 10.52,\r\n"
				+ "                \"pepMaterialId\": \"00028400695312\",\r\n"
				+ "                \"productClass\": \"\",\r\n"
				+ "                \"taxDetails\": [\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.06,\r\n"
				+ "                        \"taxAmount\": 0.58,\r\n"
				+ "                        \"taxTypeCode\": \"STATE\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0125,\r\n"
				+ "                        \"taxAmount\": 0.12,\r\n"
				+ "                        \"taxTypeCode\": \"COUNTY\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.005,\r\n"
				+ "                        \"taxAmount\": 0.05,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    },\r\n"
				+ "                    {\r\n"
				+ "                        \"taxPercent\": 0.0025,\r\n"
				+ "                        \"taxAmount\": 0.02,\r\n"
				+ "                        \"taxTypeCode\": \"DISTRICT\"\r\n"
				+ "                    }\r\n"
				+ "                ],\r\n"
				+ "                \"discountDetails\": [],\r\n"
				+ "                \"fulfillments\": [],\r\n"
				+ "                \"bundleComponents\": [],\r\n"
				+ "                \"adjustments\": [],\r\n"
				+ "                \"extendedItemAttributesMap\": {\r\n"
				+ "                    \"mdgRequestedQtyUom\": \"\",\r\n"
				+ "                    \"sourceProfileId\": \"9999\",\r\n"
				+ "                    \"routeId\": \"R00551\",\r\n"
				+ "                    \"marketPlaceAlternateOrderId\": \"995\",\r\n"
				+ "                    \"orderLocationId\": \"12212\",\r\n"
				+ "                    \"soldToCustomerId\": \"42358780\",\r\n"
				+ "                    \"preOrder\": false,\r\n"
				+ "                    \"mdgLocationId\": \"2116\",\r\n"
				+ "                    \"mdgProductId\": \"1500000641\",\r\n"
				+ "                    \"mdgRouteId\": \"USF05F\",\r\n"
				+ "                    \"marketPlaceAccountId\": \"9999\"\r\n"
				+ "                },\r\n"
				+ "                \"extendedItemAttributesList\": []\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"validations\": [\r\n"
				+ "            {\r\n"
				+ "                \"validationStatus\": \"Valid\",\r\n"
				+ "                \"processedDate\": \"2023-09-05T13:50:11.932Z\",\r\n"
				+ "                \"rules\": []\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"discounts\": [\r\n"
				+ "            {\r\n"
				+ "                \"discountAmount\": 0.0\r\n"
				+ "            }\r\n"
				+ "        ],\r\n"
				+ "        \"adjustments\": []\r\n"
				+ "    }\r\n"
				+ "]";
		
		return new ResponseEntity<String>(s, HttpStatus.OK);

	}
}
